// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoboCleanCloud.Infrastructure.Persistence;

#nullable disable

namespace RoboCleanCloud.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216180947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ErrorCode");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("CleaningErrors", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("QuietHoursEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("QuietHoursStart")
                        .HasColumnType("integer");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UTC");

                    b.PrimitiveCollection<string>("ZoneIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastTriggeredAt");

                    b.HasIndex("RobotId");

                    b.ToTable("CleaningSchedules", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AreaCleaned")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyConsumed")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string>("ZoneIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("CleaningSessions", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.MaintenanceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDaysLeft")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastReplacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHealth");

                    b.HasIndex("RobotId");

                    b.HasIndex("Type");

                    b.ToTable("MaintenanceItems", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DustbinLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionStatus");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Robots", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.RobotStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.HasIndex("Timestamp");

                    b.ToTable("RobotStatusHistories", (string)null);
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningError", b =>
                {
                    b.HasOne("RoboCleanCloud.Domain.Entities.CleaningSession", "Session")
                        .WithMany("Errors")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningSchedule", b =>
                {
                    b.HasOne("RoboCleanCloud.Domain.Entities.Robot", "Robot")
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningSession", b =>
                {
                    b.HasOne("RoboCleanCloud.Domain.Entities.Robot", "Robot")
                        .WithMany("CleaningSessions")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoboCleanCloud.Domain.Entities.CleaningSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Robot");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.MaintenanceItem", b =>
                {
                    b.HasOne("RoboCleanCloud.Domain.Entities.Robot", "Robot")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.RobotStatusHistory", b =>
                {
                    b.HasOne("RoboCleanCloud.Domain.Entities.Robot", "Robot")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.CleaningSession", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("RoboCleanCloud.Domain.Entities.Robot", b =>
                {
                    b.Navigation("CleaningSessions");

                    b.Navigation("MaintenanceItems");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
